# NumPy

Read the links: https://numpy.org/doc/stable/user/quickstart.html  and https://numpy.org/doc/stable/user/basics.broadcasting.html  before solving the exercises. 

In [3]:
import numpy as np

### Print out the dimension (number of axes), shape, size and the datatype of the matrix A.

In [4]:
A = np.arange(1, 16).reshape(3,5)

In [6]:
print(A)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [5]:
print(A.ndim)
print(A.shape)
print(A.size)
print(A.dtype)

2
(3, 5)
15
int32


### Do the following computations on the matrices B and C: 
* Elementwise subtraction. 
* Elementwise multiplication. 
* Matrix multiplication (by default you should use the @ operator).

In [7]:
B = np.arange(1, 10).reshape(3, 3)
C = np.ones((3, 3))*2

print(B)
print()
print(C)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]


In [93]:
print(B-C)
print(B*C)
print(B@C)
#print(B.dot(C)) another way to do a matrix multiplication


[[-1.  0.  1.]
 [ 2.  3.  4.]
 [ 5.  6. 16.]]
[[ 2.  4.  6.]
 [ 8. 10. 12.]
 [14. 16. 36.]]
[[12. 12. 12.]
 [30. 30. 30.]
 [66. 66. 66.]]


### Do the following calculations on the matrix:
* Exponentiate each number elementwise (use the np.exp function).

* Calculate the minimum value in the whole matrix. 
* Calculcate the minimum value in each row. 
* Calculcate the minimum value in each column. 


* Find the index value for the minimum value in the whole matrix (hint: use np.argmin).
* Find the index value for the minimum value in each row (hint: use np.argmin).


* Calculate the sum for all elements.
* Calculate the mean for each column. 
* Calculate the median for each column. 

In [96]:
B = np.arange(1, 10).reshape(3, 3)


In [97]:
print(B)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [98]:
print(np.exp(B))
print(np.min(B))
print(np.min(B, axis=1)) # axis=1 indicates rows
print(np.min(B, axis=0)) #axis=0 indicates columns
print(np.argmin(B))
print(np.argmin(B, axis=1))
print(np.sum(B))
#print(np.mean(B)) average for the whole matrix
print(np.mean(B, axis=0))
print(np.median(B, axis=0))

[[2.71828183e+00 7.38905610e+00 2.00855369e+01]
 [5.45981500e+01 1.48413159e+02 4.03428793e+02]
 [1.09663316e+03 2.98095799e+03 8.10308393e+03]]
1
[1 4 7]
[1 2 3]
0
[0 0 0]
45
5.0
[4. 5. 6.]
[4. 5. 6.]


### What does it mean when you provide fewer indices than axes when slicing? See example below.

In [56]:
print(A)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [74]:
A[1]

array([ 6,  7,  8,  9, 10])

**Answer:**

In a bidimentional matrix it takes only the row with the specified index,
while in a tridimentional matrix it takes only the matrix with the specifid index, see the example below

In [52]:
R = np.random.randint(10, size=(3,3,3))

In [68]:
print(R)

[[[3 6 3]
  [6 4 0]
  [8 0 3]]

 [[1 3 7]
  [4 6 1]
  [7 1 2]]

 [[1 8 0]
  [7 8 8]
  [5 9 0]]]


In [71]:
print(R[0])

[[3 6 3]
 [6 4 0]
 [8 0 3]]


### Iterating over multidimensional arrays is done with respect to the first axis, so in the example below we iterate trough the rows. If you would like to iterate through the array *elementwise*, how would you do that?

In [169]:
A = np.arange(1,16).reshape((3,5))
print(A)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


There are few different ways to iterate elementswise. Here I show 2. The first one is through nested for loops. It works but it is not the most efficient way. The second one through the ravel function that returns a one dimentional array

In [81]:
for i in A:
    for j in i:
        print(j)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15


In [177]:
for i in np.ravel(A):
    print(i)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15


### Explain what the code below does. More specifically, b has three axes - what does this mean? 

In [102]:
a = np.arange(30)
b = a.reshape((2, 3, -1))
#Now I create a 2d array to show the difference
c = a.reshape(5,-1)

print(a)
print()

print(b)
print()
print(c)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]
<class 'numpy.ndarray'>

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]
<class 'numpy.ndarray'>


np.arange creates an array with 30 elements with values from 0 to 29. This array is stored in the variable 'a'. Through the reshape function we create a numpy multidimentional array which has 2 new arrays with 3 subarrays each. With the third parameter we specify how many elements the subbarrays will have; if the value of the third parameter is -1 we let the function calculate automatically how many element should the subbarrays have. In this specific case it is quite obvious that if we have 30 elements the new arrays will have 15 elements each divided in 3 subbarrays which must contain solely 5 elements. Pratically we can see the reshaped array as a trimimentional 2X3X5 matrix. Every time we reshape an array with 3 parameters we create a new 3D array with the same elements. If we use 2 parameters we create a 2D array (if the second parameter is -1 we let the function calculate automatically the number of elements each row will have)

### Broadcasting
**Read the following link about broadcasting: https://numpy.org/doc/stable/user/basics.broadcasting.html#basics-broadcasting**

# Remark on Broadcasting when doing Linear Algebra calculations in Python. 

### From the mathematical rules of matrix addition, the operation below (m1 + m2) does not make sense. The reason is that matrix addition requires two matrices of the same size. In Python however, it works due to broadcasting rules in NumPy. So you must be careful when doing Linear Algebra calculations in Python since they do not follow the "mathematical rules". This can however easily be handled by doing some simple programming, for example validating that two matrices have the same shape is easy if you for instance want to add two matrices. 

In [88]:
m1 = np.array([[1, 2], [3, 4]])
m2 = np.array([1, 1])
print(m1)
print(m1 + m2)

[[1 2]
 [3 4]]
[[2 3]
 [4 5]]


### The example below would also not be allowed if following the "mathematical rules" in Linear Algebra. But it works due to broadcasting in NumPy. 

In [89]:
v1 = np.array([1, 2, 3])
print(v1 + 1)

[2 3 4]


In [92]:
A = np.arange(1, 5).reshape(2,2)
print(A)

b = np.array([2, 2])
print(b)

[[1 2]
 [3 4]]
[2 2]


# Linear Algebra Exercises

The exercies are taken from the "Matrix Algebra for Engineers" by Chasnov: https://www.math.hkust.edu.hk/~machas/matrix-algebra-for-engineers.pdf .

Do the following exercises: 
* Chapter 2, exercise 1-3.
* Quiz on p.8, exercise 2. 
* Chapter 6, exercise 1. 
* Quiz on p.15, exercise 3. 


* Chapter 10, exercise 1. 
* Chapter 12 exercise 1. 


In [237]:
A = np.array([[2, 1, -1], [1, -1, 1]])
B = np.array([[4, -2, 1], [2, -4, -2]])

C = np.array([[1, 2], [2, 1]])
D = np.array([[3, 4], [4, 3]])

E = np.array([[1], [2]])

print(A)
print(B)
print(C)
print(D)
print(E)

[[ 2  1 -1]
 [ 1 -1  1]]
[[ 4 -2  1]
 [ 2 -4 -2]]
[[1 2]
 [2 1]]
[[3 4]
 [4 3]]
[[1]
 [2]]


**Chap2. Question 1.**

**Write a function "add_mult_matrices" that takes two matrices as input arguments (validate that the input are of the type numpy.ndarray by using the isinstance function), a third argument that is either 'add' or 'multiply' that specifies if you want to add or multiply the matrices (validate that the third argument is either 'add' or 'multiply'). When doing matrix addition, validate that the matrices have the same size. When doing matrix multiplication, validate that the sizes conform (i.e. number of columns in the first matrix is equal to the number of rows in the second matrix).**

In this exercise, create a function that takes two matrices as input and either adds or multiplies them by specifying a argument as either 'add' or 'multiply'. Validate that both matrices taken as input are of the type ndarray (use the isinstance function).

In [261]:
def add_mult_matrices(m, n, operation):
    '''Here I write a function that sum and multiplicate 2 matrixes. 
       It takes 3 different parametres: the first two (m and n) are the matrixes and the third (operation) 
       is the name of the operation we want to perform.
       To ensure that the programm performs correctly the inputs must go through few levels of validification; 
       if they don't pass the validification exceptions are raised.
       The first one is controlling that the matrices I insert are instances of numpy.ndarray class.
       The we check if the name of the operation we want to perform is passed as a string and is spelled correctly.
       If these levels are passed then we can start to operate on the matrixes. 
       To add two matrixes we have to make sure that they have the same number of rows and colums.
       To multifly them, using the linear algebra definition, we have to check that the numer of columns 
       in the first matrix equals the number of rows in the second one'''
    
    
    #first validification level: checking if the matrixes are instances of numpy.ndarray class
    if (not(isinstance(m, np.ndarray) and isinstance(n, np.ndarray))):
        raise Exception("Matrices must be an instance of numpy.ndarray class")
    
    else:
        #second validificatio: checking if the operation parameter is a string
        if not(isinstance(operation,str)):
            raise Exception("The operation you want to perform must be passed as a string")
            
        else:
            #here the user can choose what operation he/she wants to perform. To avoid problems the input is case-insensitive.
            if operation.casefold() == "add":
                #fourth level of validification: controlling if the matrixes have the same number of rows and the same number of columns in order to perform a sum
                if m.shape==n.shape:
                    return m + n
                else:
                    raise Exception("You can't do this operation because the two matrix have different dimentions")
        
            elif operation.casefold() == "multiply":
                #checking if the the number of columns of the first matrix are the same as rows of the second
                if m.shape[1]==n.shape[0]:
                    return m@n
                else:
                    raise Exception("The first matrix must have the same number of columns as the second matrix has rows")
        
            else:
                raise Exception( "You specified a wrong operation or didn't spell it correctly. Try 'add' or 'multiply'")

In [262]:
print(add_mult_matrices.__doc__)

Here I write a function that sum and multiplicate 2 matrixes. 
       It takes 3 different parametres: the first two (m and n) are the matrixes and the third (operation) 
       is the name of the operation we want to perform.
       To ensure that the programm performs correctly the inputs must go through few levels of validification; 
       if they don't pass the validification exceptions are raised.
       The first one is controlling that the matrices I insert are instances of numpy.ndarray class.
       The we check if the name of the operation we want to perform is passed as a string and is spelled correctly.
       If these levels are passed then we can start to operate on the matrixes. 
       To add two matrixes we have to make sure that they have the same number of rows and colums.
       To multifly them, using the linear algebra definition, we have to check that the numer of columns 
       in the first matrix equals the number of rows in the second one


In [253]:
print(add_mult_matrices(-2*A,B,"aDD"))

[[ 0 -4  3]
 [ 0 -2 -4]]


In [254]:
print(add_mult_matrices(3*C,-E,"ADD"))

Exception: You can't do this operation because the two matrix have different dimentions

In [255]:
print(add_mult_matrices(A,C,"multiPLY"))

Exception: The first matrix must have the same number of columns as the second matrix has rows

In [256]:
print(add_mult_matrices(C,D,"multiply"))

[[11 10]
 [10 11]]


In [257]:
print(add_mult_matrices(C,B,"multiply"))

[[  8 -10  -3]
 [ 10  -8   0]]


**Chap2. Question 2**

In [178]:
A=np.array([[1,2],[2,4]])
B=np.array([[2,1],[1,3]])
C=np.array([[4,3],[0,2]])

In [179]:
print(np.array_equal(B,C))
print(np.array_equal(A@B,A@C))

False
True


**Chap2. Question 3**

In [180]:
A=np.array([[1,1,1],[1,2,3],[1,3,4]])
D=np.array([[2,0,0],[0,3,0],[0,0,4]])

In [181]:
print(A@D)
print(D@A)

[[ 2  3  4]
 [ 2  6 12]
 [ 2  9 16]]
[[ 2  2  2]
 [ 3  6  9]
 [ 4 12 16]]


**Quiz p.8, Question 2**

In [182]:
X = np.array([[1,-1],[-1,1]])
Y = np.array([[-1,1],[1,-1]])

In [183]:
print(X@Y) #Answer is a

[[-2  2]
 [ 2 -2]]


**Chap 6. Question 1**

In [184]:
M = np.array([[5,6],[4,5]])
N = np.array([[6,4],[3,3]])

In [187]:
print(np.linalg.inv(M))
print(np.linalg.inv(N))

[[ 5. -6.]
 [-4.  5.]]
[[ 0.5        -0.66666667]
 [-0.5         1.        ]]


**Quiz p.15, Question 3**

In [189]:
K = np.array([[2,2],[1,2]])

In [190]:
print(np.linalg.inv(K)) #Answer is a

[[ 1.  -1. ]
 [-0.5  1. ]]


**Chap10. Question 1 a)**

In [191]:
A = np.array([[3,-7,-2],[-3,5,1],[6,-4,0]])
X = np.array([-7,5,2])


In [192]:
print(np.linalg.solve(A,X))

[ 3.  4. -6.]


**Chap10. Question 1 b)**

In [193]:
B = np.array([[1,-2,3],[-1,3,-1],[2,-5,5]])
Y = np.array([1,-1,1])


In [194]:
print(np.linalg.solve(B,Y))

[ 8.  2. -1.]


**Chap 12. Question 1**

In [195]:
M = np.array([[3,-7,-2],[-3,5,1],[6,-4,0]])

In [196]:
print(np.linalg.inv(M))

[[ 0.66666667  1.33333333  0.5       ]
 [ 1.          2.          0.5       ]
 [-3.         -5.         -1.        ]]


### Copies and Views
Read the following link: https://numpy.org/doc/stable/user/basics.copies.html

**Basic indexing creates a view, How can you check if v1 and v2 is a view or copy? If you change the last element in v2 to 123, will the last element in v1 be changed? Why?**

In [267]:
v1 = np.arange(4)
v2 = v1[-2:]
print(v1)
print(v2)

[0 1 2 3]
[2 3]


In [268]:
# The base attribute of a view returns the original array while it returns None for a copy.
print(v1.base)
v2.base

None


array([0, 1, 2, 3])

In [270]:
# The last element in v1 will be changed aswell since v2 is a view, meaning they share the same data buffer.
v1[0] = 123
print(v1)
print(v2)

[123   1   2 123]
[  2 123]


To check if v2 is a copy of v1 we can check if it has a shared or a separate memory. This can be done accessing the base attribute: if it returns an array then the memory is shared and v2 is a view. If it returns none that means that v2 is a copy hence a new array on its own. Since the memory of a view is shared if we change some of its elements also the original array will change likewise. Viceversa, if we change an element of the original array included in the view also the element in the view will change